In [2]:
f1=open("emp.csv","r")
f2=open("sal.csv","r")
f3=open("emp_sal","w")

content1=f1.read()
content2=f2.read()

name=[]
sal=[]

lines1=content1.split("\n")
lines2=content2.split("\n")

for l1 in lines1:
  words1=l1.split(",")

  for l2 in lines2:
    words2=l2.split(",")
    if(words1[0]==words2[0]):
      l1=l1 + "," + words2[1] + "," + words2[2] + "\n"
      f3.write(l1)
      name.append(words1[1])
      sal.append(int(words2[2]))
      print(l1)

f1.close()
f2.close()
f3.close()

print(name)

print(sal)

1,Sanvi,Manager,100000,Manager,100000

2,Mrunmayee,Sr. Manager,95000,Sr. Manager,150000

3,Jayesh,Manager,80000,Manager,90500

4,Gouri,Sr. Manager,95000,Sr. Manager,100500

5,Mahesh,Supervisor,500000,Supervisor,85000

['Sanvi', 'Mrunmayee', 'Jayesh', 'Gouri', 'Mahesh']
[100000, 150000, 90500, 100500, 85000]