In [25]:
f=open("emp.csv","r")

contents=f.read()

lines=contents.split("\n")

eid=[]
name=[]
des=[]
sal=[]

for l in lines:
  words=l.split(",")
  print(words)
  eid.append(int(words[0]))
  name.append(words[1])
  des.append(words[0])
  sal.append(int(words[3]))

print("Employee Id",eid)
print("Employee Name",name)
print("Employee Designation",des)
print("Employee Salary",sal)

print("Maximum Salary",max(sal))

print("Minimum Salary",min(sal))

print("Average Salary",(sum(sal)/len(sal)))


print("Employee with maximum salary:",name[sal.index(max(sal))])

print("Employee with minimum salary:",name[sal.index(min(sal))])

print("Sr managers are",end=" ")
for i in range(len(des)):
  if des[i]=='Sr. Manager':
    print(name[i],end=" ")

print("Employee having salary 80000:",end=" ")
for i in range(len(sal)):
  if sal[i]==80000:
    print(name[i],end=" ")

print("Employee having salary 70000:",end=" ")
for i in range(len(sal)):
  if sal[i]==70000:
    print(name[i])
  else:
    print("No Employee has salary 70000")

['1', 'Sanvi', 'Manager', '100000']
['2', 'Mrunmayee', 'Sr. Manager', '95000']
['3', 'Jayesh', 'Manager', '80000']
['4', 'Gouri', 'Sr. Manager', '95000']
['5', 'Mahesh', 'Supervisor', '500000']
Employee Id [1, 2, 3, 4, 5]
Employee Name ['Sanvi', 'Mrunmayee', 'Jayesh', 'Gouri', 'Mahesh']
Employee Designation ['1', '2', '3', '4', '5']
Employee Salary [100000, 95000, 80000, 95000, 500000]
Maximum Salary 500000
Minimum Salary 80000
Average Salary 174000.0
Employee with maximum salary: Mahesh
Employee with minimum salary: Jayesh
Sr managers are Employee having salary 80000: Jayesh Employee having salary 70000: No Employee has salary 70000
No Employee has salary 70000
No Employee has salary 70000
No Employee has salary 70000
No Employee has salary 70000